# Generated by Django 2.0.3 on 2018-06-03 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagedetail',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
