# Generated by Django 2.0.3 on 2018-06-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180603_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecategory',
            name='nums',
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='分类名称'),
        ),
    ]
