# Generated by Django 2.0.3 on 2018-06-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180603_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagedetail',
            name='tags',
            field=models.CharField(default='', max_length=50, verbose_name='标签'),
        ),
    ]
