# Generated by Django 2.0.3 on 2018-06-03 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180603_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='lasting_time',
            field=models.IntegerField(default=0, verbose_name='运行时间(天)'),
        ),
    ]
