# Generated by Django 2.0.3 on 2018-06-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180603_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagedetail',
            name='is_lunbo',
            field=models.BooleanField(default=False, verbose_name='是否轮播'),
        ),
    ]
