# Generated by Django 2.0.3 on 2018-06-06 23:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_pagedetail_is_lunbo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archiving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_category', models.DateField(default=datetime.date.today, verbose_name='归档日期')),
                ('nums', models.IntegerField(default=0, verbose_name='文章数量')),
            ],
            options={
                'verbose_name': '文章归档',
                'verbose_name_plural': '文章归档',
            },
        ),
    ]
