# Generated by Django 2.0.3 on 2018-06-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_archiving'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archiving',
            name='time_category',
        ),
        migrations.AddField(
            model_name='archiving',
            name='month',
            field=models.IntegerField(default=6, verbose_name='归档月份'),
        ),
        migrations.AddField(
            model_name='archiving',
            name='year',
            field=models.IntegerField(default=2018, verbose_name='归档年份'),
        ),
    ]
