# Generated by Django 2.0.3 on 2018-06-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='lasting_time',
        ),
    ]
