# Generated by Django 2.0.3 on 2018-06-09 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_siteinfo_lasting_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='article_nums',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='category_nums',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='comments_nums',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='tag_nums',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='total_views',
        ),
    ]
