# Generated by Django 2.0.3 on 2018-07-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180609_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archiving',
            name='nums',
        ),
        migrations.AlterField(
            model_name='archiving',
            name='month',
            field=models.IntegerField(default=7, verbose_name='归档月份'),
        ),
    ]
