# Generated by Django 2.0.3 on 2018-07-17 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180717_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='nums',
        ),
    ]
