# Generated by Django 2.0.3 on 2018-07-25 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_tags_nums'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router', models.CharField(max_length=50, verbose_name='访问路由')),
                ('remote_addr', models.CharField(max_length=20, verbose_name='ip地址')),
                ('visited_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='访问时间')),
            ],
            options={
                'verbose_name': '网站访问统计',
                'verbose_name_plural': '网站访问统计',
            },
        ),
    ]
