# Generated by Django 2.0.3 on 2018-07-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_tracecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracecount',
            name='method',
            field=models.CharField(default='GET', max_length=8, verbose_name='访问方式'),
        ),
    ]
