# Generated by Django 2.0.3 on 2018-05-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailvarifyrecord',
            name='token',
            field=models.CharField(blank=True, max_length=26, null=True, verbose_name='凭证'),
        ),
    ]
